name: Run Go Script

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Run Go script
      run: |
        cd go
        go run main.go

    - name: Commit and push if it changed
      run: |
        git diff
        git add .
        git config --global user.email "naa0@lguplus.co.kr"
        git config --global user.name "i-zro"
        git commit -m "Update habit files" --allow-empty
        git push origin gh-pages
